FROM python:3.11-slim

# Dependencias críticas de sistema[cite: 2, 3]
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Librerías de NetPro: FastAPI, ipaddress para red, hashlib, etc.[cite: 2, 3]
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]