export const styles = {
  container: {
    minHeight: '100vh',
    background: 'var(--np-bg)',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    background: 'var(--np-surface)',
    borderBottom: '1px solid var(--np-border-strong)',
    padding: '8px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    flexShrink: 0,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  headerRight: {
    display: 'flex',
    gap: '10px',
  },
  main: {
    flex: 1,
    padding: '20px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  card: {
    width: '100%',
    maxWidth: '960px',
    background: 'var(--np-accent)',
    borderRadius: '10px',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  cardTitle: {
    margin: 0,
    color: '#fff',
    fontWeight: '700',
    fontSize: '1.4rem',
  },
  alert: (isError) => ({
    background: isError ? 'rgba(212,15,15,0.18)' : 'rgba(255,255,255,0.08)',
    border: `1px solid ${isError ? '#ff4444' : 'rgba(255,255,255,0.25)'}`,
    borderRadius: '6px',
    padding: '10px 14px',
    color: '#fff',
    fontSize: '0.82rem',
    fontFamily: 'JetBrains Mono, monospace',
  }),
  contentGrid: {
    display: 'flex',
    gap: '24px',
    flexWrap: 'wrap',
  },
  column: {
    flex: '1 1 280px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    marginTop: '14px',
  },
  checkboxGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    cursor: 'pointer',
    color: '#fff',
    fontSize: '0.85rem',
  },
  useSubnetBtn: {
    background: 'rgba(83,238,255,0.15)',
    border: '1px solid var(--np-cyan)',
    color: 'var(--np-cyan)',
    borderRadius: '5px',
    padding: '7px 14px',
    fontSize: '0.78rem',
    cursor: 'pointer',
    fontWeight: '600',
    letterSpacing: '0.02em',
  },
  vlsmGroup: {
    marginTop: '14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  vlsmInputGroup: {
    display: 'flex',
    gap: '8px',
  },
  vlsmResultBox: {
    background: '#1a2332',
    borderRadius: '8px',
    padding: '14px',
    minHeight: '180px',
    flex: 1,
  },
  vlsmEfficiency: {
    background: 'rgba(0,96,127,0.2)',
    border: '1px solid rgba(83,238,255,0.2)',
    borderRadius: '6px',
    padding: '8px 12px',
    fontSize: '0.72rem',
    color: 'var(--np-text-dim)',
    fontFamily: 'JetBrains Mono, monospace',
  },
  vlsmRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '5px 0',
    borderBottom: '1px solid rgba(255,255,255,0.05)',
  },
  vlsmLabel: {
    color: 'var(--np-text-dim)',
    fontSize: '0.77rem',
  },
  vlsmValue: {
    color: 'var(--np-cyan)',
    fontSize: '0.78rem',
    fontFamily: 'JetBrains Mono, monospace',
    fontWeight: '500',
  },
};
